### ISSUE TITLE
Status & License of the system

### ISSUE THREAD

**Issue by RadoRado** [valo/maycamp_arena#78]
Hello there @valo ;)

We found that we need a grading system for some of our courses (HackBulgaria) and we started researching possibilities, which come down to two things:

* Implement our own system (probably NodeJS stack + python for a runner)
* Use an existing system that can be customized to our needs.

Maycamp looks great and I have used it when I was a student, having an Algo course at FMI.

So I have a few starting questions:

* What is the status of Maycamp? Is it still supported?
* What is the License? Can we fork it and adjust it to our needs?

Cheers!

**Comment by valo** [comment]
Hi @RadoRado,

The project is actively developed as you can see from the commit history :) It is deployed on http://arena.maycamp.com/ and used actively every day. There are usually over 50 source codes sent daily.

We haven't added a license in the project as this has never been brought up, but I think we can assume it is released under the MIT license as it is the most liberal :-)

I will be very happy if you can propose features that can be merged back into the main project. What features do you need at the moment? I recently re-implemented the sandboxing system to use docker, so it supports virtually any language.

**Comment by RadoRado** [comment]
@valo This is great news! Active development is always a good thing to have.

I think we should partner somehow.

In HackBulgaria, we will benefit a lot from such a system. There is also an algo course coming up and we plan to make it really good & big.

**I have 2 more questions:**

* How many active contributors you have right now?
* Why don't you support Python 3.4 (3.*) rather than Python 2.7? Python 2 must and should die.

**Also, there are few things that I think we can do:**

* Since we need such a system, we can invest in contributors to keep working on that system. Or provide our own people helping here. Does this sound viable?
* I think we need to run our own instance of the Maycamp arena since we have our own infrastructure of courses & students. But keeping all the problems in one place can also be a good thing. What is your opinion here?

About new features, without giving enough time for my thoughts to form something clear, here are few suggestions:

* Make it possible to login with external API / import extrnal database with users. This is for our case.
* Make it possible to export back information about problems to that external database.
* Migrate from Python 2 to Python 3 for problems.
* Add few more languages like Haskell & JavaScript (Node).
* Remove the PDF problems description.
* Sync problem descriptions from a GitHub repository. Want to make a new contest? Great. Say which folder in which GitHub repo holds the proble statements (in a given format) & import them to database.
* Make it possible to test discrete parts of code (like functions, running with tests), without the need to implement an entire program.
* Re-style the entire thing.
* Add more hierarchy to contests. Such as - contests are happening in a course. Each course can have tags which serves as filtering.

But as I said - I just drafted them by exploring the system & looking for what our needs are.

I will be happy if you provide some input on my questiosn above. I will be extremely happy if we can find a way to collaborate ^_^

**Comment by valo** [comment]
About your questions:

> How many active contributors you have right now?

Currently I am the only one contributing code to the project. I have plans to simplify the code, so that it is more understandable and with better test coverage (currently there is a cucumber test suite and a set of manually gathered tests for the sandboxing). It will be great if other people can be involved, so that the project grows bigger and better. I can provide guidance in the code if needed.

> Why don't you support Python 3.4 (3.*) rather than Python 2.7? Python 2 must and should die.

There is no particular reason actually. It can be swapped with python 3 very easy and even both versions can be supported. The current sandboxing system was a POC and I included Java and Python 2 as examples how different languages can be supported.

> Since we need such a system, we can invest in contributors to keep working on that system. Or provide our own people helping here. Does this sound viable?

As I said: I will be very happy is more people get involved in the project. Let's talk on skype about this :smile: 

> I think we need to run our own instance of the Maycamp arena since we have our own infrastructure of courses & students. But keeping all the problems in one place can also be a good thing. What is your opinion here?

I can help you with running your own instance of the system. I have capistrano and ansible tasks for doing a deployment from scratch, but it might need polishing. I can provide you with support in deploying the system.

You can use the current deployment too. The system can handle the load without problems. I have a backup grading server, which I need to bring online. It is in a colocation center with backup power and internet. This way there will be 2 separate grading servers making the grader fault tolerant. The web part is hosted on digital ocean in Amsterdam and it is rock solid. The grading and the web are on 2 different machines, so that if someone manages to hack the sandboxing part the site will continue to operate.

About your suggestions:

> Make it possible to login with external API / import extrnal database with users. This is for our case.

I was thinking some time ago to add facebook/gmail/oauth login. About import of a user DB: we need to think what will be the best way to approach this (CSV import probably?)

> Make it possible to export back information about problems to that external database

It is currently possible to download all the sources for a given contest as a zip file from the admin panel. I can give you admin permissions to have a look at it.

> Migrate from Python 2 to Python 3 for problems

The migration from python 2 to 3 will be trivial

> Add few more languages like Haskell & JavaScript (Node).

Adding more languages should be trivial

> Remove the PDF problems description.

Do you have an idea for other formats of the problem description? I think it will be easy to add support for other formats, like markdown. We just need to define the convention for that.

> Sync problem descriptions from a GitHub repository. Want to make a new contest? Great. Say which folder in which GitHub repo holds the proble statements (in a given format) & import them to database

You can have a look at the current problem format here: https://github.com/valo/maycamp_arena/wiki/Format-of-the-tasks. I also had the idea to support task/contest packages and documented my thoughts here: https://github.com/valo/maycamp_arena/wiki/Contest-and-task-packages but the idea didn't get tracktion and I gave up on it. Importing a git repo/folder is an interesting idea. Do you have a example repo with an example layout?

> Make it possible to test discrete parts of code (like functions, running with tests), without the need to implement an entire program.

I think making it possible to test isolated functions is a great idea! It shouldn't be that hard to implement too. Just provide a source template with each problem and the system can take the user's source code and insert it into the template. It doesn't look like a hard feature to implement.

> Re-style the entire thing.

Styling will be a tough thing. It will be great if the whole restyling could be done in CSS only, but that will be a hard task. I think we can have a skype meeting and discuss this. It really depends on the design and the details around it.

> Add more hierarchy to contests. Such as - contests are happening in a course. Each course can have tags which serves as filtering.

Currently we have a tagging system, which is not publicly available: http://arena.maycamp.com/categories It is not completely ready but it allows to tag problems. Additional hierarchy will be valuable, but also we should be careful not to make it too complicated. It will be interesting to see what will be the simplest thing that will do the job.

If you want we can chat on skype about all this. I will be happy to hear your ideas and provide feedback and help. My skype is valo_bg.

**Comment by RadoRado** [comment]
@valo thank you very much for the great answers!

Lets do a skype call next monday. I will contact you via email for more information :+1:

**Comment by valo** [comment]
Closing this as the discussion is going on in other channels
